app/blueprints/product/__init__.py
from flask import Blueprint

prod_bp = Blueprint('prod', __name__)

from . import routes  # Import routes to register them

app/blueprints/product/routes.py
import os

from flask import render_template, redirect, url_for, request, flash, current_app
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename

from . import prod_bp
from app.models import Product, Category
from app.forms import ProductForm
from ... import db


@prod_bp.route('/<int:product_id>', methods=['GET'])
def product_detail(product_id):
    # Fetch the product details using the product_id
    product = Product.query.get_or_404(product_id)
    return render_template('app/product_detail.html', product=product)

@login_required
@prod_bp.route('/edit/<int:pk>', methods=['GET', 'POST'])
def product_edit(pk):
    product = Product.query.filter_by(id=pk, seller=current_user).first_or_404()
    if request.method == "POST":
        form = ProductForm(request.form)
        if form.validate_on_submit():
            product.title = form.title.data
            product.description = form.description.data
            product.price = form.price.data
            product.location = form.location.data
            product.image = form.image.data
            new_category_name = request.form.get("new_category")
            if new_category_name:
                new_category = Category()
                new_category.name = new_category_name
                product.category = new_category
            else:
                selected_category = request.form.get("category")
                if selected_category:
                    product.category = Category.query.get(selected_category)
            product.seller = current_user
            db.session.add(product)
            db.session.commit()
            return redirect(url_for('main.home'))
        if form.errors:
            print(form.errors.values())

    else:
        form = ProductForm(obj=product)

    categories = Category.query.all()
    return render_template('app/product_edit.html', form=form, product=product, categories=categories)


@prod_bp.route('/create', methods=['GET', 'POST'])
@login_required
def product_create():
    form = ProductForm()
    if form.validate_on_submit():
        product = Product()
        product.title = form.title.data
        product.description = form.description.data
        product.price = form.price.data
        product.location = form.location.data
        product.seller = current_user

        if form.image.data:
            image_file = form.image.data
            filename = secure_filename(image_file.filename)
            image_path = os.path.join(current_app.root_path, 'static', 'media/product_images', filename)
            image_file.save(image_path)
            product.image = f'media/product_images/{filename}'

        new_category_name = request.form.get("new_category")
        if new_category_name:
            new_category = Category(name=new_category_name)
            db.session.add(new_category)
            db.session.flush()  # To generate the ID of the new category
            product.category = new_category
        else:
            selected_category = request.form.get("category")
            if selected_category:
                product.category_id = selected_category

        db.session.add(product)
        db.session.commit()
        return redirect(url_for('main.home'))

    return render_template('app/product_form.html', form=form, categories=Category.query.all())


@login_required
@prod_bp.route('/delete/<int:pk>', methods=['POST'])  # POST method for deletion
def delete(pk):
    # Get product by primary key and seller
    product = Product.query.filter_by(id=pk, seller=current_user).first_or_404()

    db.session.delete(product)  # Delete the product from the session
    db.session.commit()  # Commit the deletion to the database

    flash('Product deleted successfully!', 'success')  # Flash a success message
    return redirect(url_for('prof.profile'))  # Redirect to the profile

app/blueprints/profile/__init__.py
from flask import Blueprint

prof_bp = Blueprint('prof', __name__)

from . import routes  # Import routes to register them

app/blueprints/profile/routes.py
from flask import render_template, request, current_app
from flask_login import login_required, current_user
from app import db
from . import prof_bp

from werkzeug.utils import secure_filename
import os


@prof_bp.route('/', methods=['GET', 'POST'])
@login_required
def profile():
    if request.method == 'POST' and 'profile_picture' in request.files:
        file = request.files['profile_picture']
        if file:
            filename = secure_filename(file.filename)
            profile_dir = os.path.join(current_app.static_folder, 'media/profile_pics')

            # Ensure the profile_pics directory exists
            if not os.path.exists(profile_dir):
                os.makedirs(profile_dir)

            file_path = os.path.join(profile_dir, filename)
            file.save(file_path)

            # Update the user's profile picture path in the database
            current_user.profile.profile_picture = f'media/profile_pics/{filename}'
            db.session.commit()

    return render_template('app/profile.html')  # Update to use the correct template

app/templates/app/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ product.title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='app/css/style.css') }}">
    
    <style>
        body {
            font-family: 'Arial', sans-serif; /* Modern font */
            margin: 0;
            padding: 0;
            background-color: #f8f9fa; /* Light background for contrast */
        }
        
        .container {
            max-width: 1200px; /* Centered layout */
            margin: 20px auto; /* Space around the container */
            padding: 20px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1); /* Subtle shadow for depth */
            background-color: white; /* White background for the card */
            border-radius: 8px; /* Rounded corners */
        }
        
        .back-button {
            text-decoration: none;
            color: #007bff; /* Bootstrap primary color */
            font-size: 16px;
            margin-bottom: 20px;
            display: inline-block;
        }
        
        .product-detail {
            display: flex;
            align-items: flex-start; /* Align items at the start */
        }
        
        .image-section {
            flex: 1; /* Flexbox to make image section responsive */
            max-width: 400px; /* Limit image size */
        }
        
        .product-image {
            width: 100%; /* Responsive image */
            height: auto; /* Maintain aspect ratio */
            border-radius: 8px; /* Rounded image corners */
        }
        
        .info-section {
            flex: 2; /* Take more space for info section */
            padding-left: 20px; /* Space between image and info */
        }
        
        .product-title {
            font-size: 24px; /* Larger title font size */
            color: #333; /* Dark text color */
            margin: 0;
        }
        
        .price {
            font-size: 20px; /* Highlight price */
            color: #f26522; 
            margin: 10px 0;
        }
        
        .description {
            font-size: 16px; /* Description font size */
            line-height: 1.5; /* Better readability */
            margin: 10px 0;
        }
        
        .btn {
            padding: 10px 15px; /* Button padding */
            border: none; /* No border */
            border-radius: 5px; /* Rounded button */
            background-color: #007bff; /* Button color */
            color: white; /* White text */
            font-size: 16px; /* Button font size */
            cursor: pointer; /* Pointer cursor on hover */
            transition: background-color 0.3s; /* Smooth hover effect */
        }
        
        .btn:hover {
            background-color: #0056b3; /* Darker blue on hover */
        }

    </style>
    
</head>
<body>
    <div class="container">
        <a href="{{ url_for('main.home') }}" class="back-button">← Back to Home</a>
        <div class="product-detail">
            <div class="image-section">
                {% if product.image %}
                    <img src="{{ url_for('static', filename=product.image) }}" alt="{{ product.title }}" class="product-image">
                {% else %}
                    <img src="{{ url_for('static', filename='utils_img/default_product.png') }}" alt="Default Image" class="product-image">
                {% endif %}
            </div>
            <div class="info-section">
                <h1 class="product-title">{{ product.title }}</h1>
                <p class="price">${{ product.price }}</p>
                <p class="description">{{ product.description }}</p>
                <div class="button-section">
                {% if product.seller == current_user %}
                    <a href="{{ url_for('prod.product_edit', pk=product.id) }}" class="edit-btn">Edit Product</a>
                {% else %}
                    <button class="btn">Call Seller</button>
                {% endif %}
            </div>

            </div>
        </div>
    </div>
</body>
</html>

app/templates/app/product_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Product</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='app/css/style.css') }}">
    <link rel="stylesheet" type="text/css"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f7f7f7;
            margin: 0;
            padding: 20px;
        }

        .container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        .form-group {
            margin-bottom: 15px;
            display: flex;
            flex-direction: column;
        }

        label {
            font-weight: bold;
            color: #2b2a29;
        }

        select, input[type="text"], input[type="number"], input[type="file"], textarea {
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            transition: border-color 0.3s;
        }

        button {
            padding: 10px;
            background-color: #f26522;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s;
            margin-top: 15px;
        }

        .back-link {
            display: block;
            text-align: center;
            margin-top: 20px;
            text-decoration: none;
            color: #f26522;
        }

        /* Category section */
        .category-section {
            display: flex;
            flex-direction: column;
            gap: 10px;
        }

        .category-section input[type="text"] {
            flex-grow: 1;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Edit Product</h1>
        <form method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {% for field in form %}
                {% if field.name != 'category' and field.name != 'csrf_token' %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% if field.errors %}
                            <div class="error-message" style="color: red;">{{ field.errors }}</div>
                        {% endif %}
                    </div>
                {% endif %}
            {% endfor %}

            <!-- Unified Category Section -->
            <div class="form-group category-section">
                <label for="category">Category</label>
                <select name="category" id="category">
                    <option value="">Select Category</option>
                    {% for category in categories %}
                        <option value="{{ category.id }}" {% if product.category.id == category.id %}selected{% endif %}>
                            {{ category.name }}
                        </option>
                    {% endfor %}
                </select>
                <input type="text" name="new_category" id="new-category" placeholder="Or add a new category">
            </div>

            <button type="submit">Save Changes</button>
        </form>
        <!-- pop up start -->
        <div id="delete-popup" class="popup-overlay">
            <div class="popup-content">
                <h3>Confirm Account Deletion</h3>
                <p>Are you sure you want to delete this product? This action cannot be undone.</p>
                <button onclick="submitDelete()" class="confirm-btn">Yes, Delete</button>
                <button onclick="closePopup()" class="cancel-btn">Cancel</button>
            </div>
        </div>

        <form method="post" action="{{ url_for('prod.delete', pk=product.id) }}" id="delete-form">
            <button type="button" class="delete-btn" onclick="confirmDelete()">Delete Product</button>
        </form>

        <!-- pop up end -->
        <a href="{{ url_for('prof.profile') }}" class="back-link">Back to Profile</a>
    </div>
    <script src="{{ url_for('static', filename='app/js/script.js') }}"></script>
    <script>
        document.getElementById("id_image").addEventListener("change", function(event) {
            const file = event.target.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = function(e) {
                    document.getElementById("imagePreview").src = e.target.result;
                };
                reader.readAsDataURL(file);
            }
        });
    </script>
</body>
</html>

app/templates/app/product_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add New Product</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='app/css/style.css') }}">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f7f7f7;
            margin: 0;
            padding: 20px;
        }

        .container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        .form-group {
            margin-bottom: 15px;
            display: flex;
            flex-direction: column;
        }

        label {
            font-weight: bold;
            color: #2b2a29;
        }

        select, input[type="text"], input[type="number"], input[type="file"], textarea {
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            transition: border-color 0.3s;
        }

        button {
            padding: 10px;
            background-color: #f26522;
            color: black;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s;
            margin-top: 15px;
        }

        .back-link {
            display: block;
            text-align: center;
            margin-top: 20px;
            text-decoration: none;
            color: #f26522;
        }

        /* Category section */
        .category-section {
            display: flex;
            flex-direction: column;
            gap: 10px;
        }

        .category-section input[type="text"] {
            flex-grow: 1;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Add New Product</h1>
        <form method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {% for field in form %}
                {% if field.name != 'category' and field.name != 'csrf_token' %} {# Exclude default category field #}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        {% if field.errors %}
                            <div class="error-message" style="color: red;">{{ field.errors }}</div>
                        {% endif %}
                    </div>
                {% endif %}
            {% endfor %}

            <!-- Custom Category Section -->
            <div class="form-group category-section">
                <label for="category">Category</label>
                <select name="category" id="category">
                    <option value="">Select Category</option>
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
                <input type="text" name="new_category" id="new-category" placeholder="Or add a new category">
            </div>

            <button type="submit" class="save-btn">Add Product</button>
        </form>

        <a href="{{ url_for('main.home') }}" class="back-link">Back to Home</a>
    </div>
</body>
</html>

app/templates/app/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='app/css/style.css') }}">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f7f7f7;
            color: #333;
            margin: 0;
            padding: 20px;
        }

        .container {
            max-width: 800px;
            margin: auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        .profile-header {
            text-align: center;
        }

        .profile-picture {
            width: 150px;
            height: 150px;
            border-radius: 50%;
            object-fit: cover;
            margin-bottom: 20px;
            cursor: pointer;
        }

        h1 {
            color: #2b2a29;
        }

        .back-link {
            display: block;
            margin-top: 20px;
            text-align: center;
            text-decoration: none;
            color: #f26522;
        }

        .back-link:hover {
            text-decoration: underline;
        }

        .product-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            padding: 20px 0;
        }

        .product-card {
            position: relative;
            border: 1px solid #ddd;
            text-align: center;
            transition: transform 0.3s ease, box-shadow 0.3s ease;
            background-color: #ffffff;
            padding: 20px;
            box-shadow: 0px 0 30px 10px #f0f0f0;
            margin-bottom: 20px;
        }

        .product-card img {
            width: 100%;
            height: auto;
            object-fit: cover;
            border-radius: 4px;
        }

        .add-product-btn, .delete-account-btn, .back-home-btn {
            padding: 10px;
            background-color: #f26522;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            margin-top: 20px;
        }

        .add-product-btn:hover, .delete-account-btn:hover, .back-home-btn:hover {
            background-color: #e0571b;
        }

        .delete-account-btn {
            background-color: #d9534f;
        }

        .delete-account-btn:hover {
            background-color: #c9302c;
        }

        .popup-overlay {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.5);
            justify-content: center;
            align-items: center;
        }

        .popup-content {
            background: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
            text-align: center;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="profile-header">
        <h1>{{ current_user.username|title }}'s Profile</h1>
        <img id="profile_picture" src="{{ url_for('static', filename=current_user.profile.profile_picture) }}" alt="Profile Picture" class="profile-picture" onclick="document.getElementById('uploadInput').click();">
        <form id="uploadForm" method="POST" enctype="multipart/form-data" action="{{ url_for('prof.profile') }}">
            <input type="file" id="uploadInput" name="profile_picture" style="display: none;" onchange="uploadPicture()">
        </form>
    </div>

    {% if not current_user.products %}
        <h2 class="my-products-title">No products yet!</h2>
        <a href="{{ url_for('prod.product_create') }}" class="add-product-btn">Add Product</a>
    {% else %}
        <h2>My Products</h2>
        <div class="product-grid">
            {% for product in current_user.products %}
                <a href="{{ url_for('prod.product_edit', pk=product.id) }}" class="product-link">
                    <div class="product-card">
                        <h4 class="product_name">{{ product.title }}</h4>
                        {% if product.image %}
                            <div class="img">
                                <img src="{{ url_for('static', filename=product.image) }}" alt="{{ product.title }}">
                            </div>
                        {% else %}
                            <div class="product_img">
                                <img src="{{ url_for('static', filename='utils_img/default_product.png') }}" alt="Default Image">
                            </div>
                        {% endif %}
                        <p class="description">{{ product.description }}</p>
                        <p class="price">${{ product.price }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
    {% endif %}

    <a href="{{ url_for('main.home') }}" class="back-home-btn">Back to Home</a>
    <form method="post" action="{{ url_for('auth.delete_account') }}" id="delete-form">
        <button type="button" class="delete-btn" onclick="confirmDelete()">Delete Account</button>
    </form>
</div>

<div id="delete-popup" class="popup-overlay">
    <div class="popup-content">
        <h3>Confirm Account Deletion</h3>
        <p>Are you sure you want to delete your account? This action cannot be undone.</p>
        <button onclick="submitDelete()" class="confirm-btn">Yes, Delete</button>
        <button onclick="closePopup()" class="cancel-btn">Cancel</button>
    </div>
</div>

<script src="{{ url_for('static', filename='app/js/script.js') }}"></script>
</body>
</html>